### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Guozhongyuan** [sisl/LOPR#1]
Great work! May I ask you for more details about the dataset? Such as the resolution, type, and time interval of point cloud projection.

**Comment by BenQLange** [comment]
Thanks! 

We are using Nuscenes dataset. The OGM dimension is H × W = 128 × 128 with 0.(3) m resolution, corresponding to a 42.7m × 42.7m grid. In the prediction task, we provide 5 past OGMs as observations, and predict for 15 frames into the future at 10 Hz.

You can find more details in our preprint https://arxiv.org/pdf/2210.01249.pdf.
